### ISSUE TITLE
Update and improve the build/release process

### ISSUE THREAD

**Issue by metaphori** [scafi/scafi#27]
Refer to scafi branch [feature-build-more](https://github.com/scafi/scafi/tree/feature-build-more), in which refactoring & extensions of the build/deployment process are (being) implemented.
The following build- and release-related activities should be implemented:

* Docs (generated via unidoc) on surge.sh (http://scafi-docs.surge.sh & http://scafi-docs-unstable.surge.sh for master and develop branches, resp.)
* Publishing of the far JAR (via sbt-assembly) of the scafi-core to GitHub Releases
* Upgrade build from sbt 0.13 to sbt 1.1
* Migrate from sbt-release to sbt-release-early (which provides an DVC-integrated release process)
* Release of artifacts to Sonatype staging repos from Travis

**Comment by metaphori** [comment]
I've tried quite a bit with `sbt-release-early` but it is quite cumbersome to use.

These are some issues I experienced

- `Found multiple staging repositories` https://github.com/jvican/sbt-release-early/issues/34
- ` Failed: signature-staging, failureMessage:Missing Signature: '/it/unibo/apice/[secure]/scafi-commons_2.13/0.3.3-rc+20200407-1505/scafi-commons_2.13-0.3.3-rc+20200407-1505.pom.asc' does not exist for 'scafi-commons_2.13-0.3.3-rc+20200407-1505.pom'.`: https://travis-ci.org/github/scafi/scafi/jobs/672123661
    - Apparently, this happens 
- `[error] java.io.IOException: Supplied file /home/travis/build/scafi/scafi/target/sonatype-staging/0.3.3-rc+20200407-1520 is a not an existing directory!` https://travis-ci.org/github/scafi/scafi/jobs/672124005
- `java.lang.RuntimeException: Version and dynver mismatch - version: 0.3.3-rc+20200407-1603, dynver: 0.3.3-rc+20200407-1604` https://travis-ci.org/github/scafi/scafi/jobs/672124164
- Not to mention that I come across `sbt-release-early` asking me for BINTRAY_USER https://github.com/jvican/sbt-release-early/issues/34#issuecomment-585294080

Therefore, I think it is the case to switch to a Gradle build as per branch `feature-build-gradle`

**Comment by cric96** [comment]
I think we should decide which build system to keep, also in view of the change from Ci #57 #58. Using both SBT and Gradle might be hard to maintain.

Current situation (for what I have understan):

- Using Gradle only, introduce problems for cross-target projects since there is no Gradle plugin in support for that (this [one](https://github.com/gtache/scalajs-gradle) is apparently dead). But, on the other hand, help up in the publishing process.

- Using SBT only introduces problems for publishing artifacts, but on the other hand gives us strong support for [cross-targeting](https://github.com/portable-scala/sbt-crossproject) (both for js and native).

Overall it seems that SBT is a better fit for Scala, unfortunately I understand that its "non-industry" nature can (and has) lead to some problems. On the other hand, Scala support on Gradle does not have the same user base as SBT, and again several bugs can emerge in communitu plugins (like this [one](https://github.com/ADTRAN/gradle-scala-multiversion-plugin/issues/39)).

In any case, I would say let us make a decision and focus only on one building system, also considering our limited manpower. @metaphori what do you think?

**Comment by metaphori** [comment]
@cric96 I agree. I think we should stick to SBT which is standard for Scala projects and might be key when using certain features.
